name: MACGYVER
on:
  workflow_dispatch:

jobs:
  build:
  name: Start Building...
  runs-on: windows-latest

  steps:
    - name: Downloading & installing Essentials
      run:
        Invoke-webReqest -Uri "https://gitlab.com/chamod12/lm_win10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
        cmd /c Downloads.bat

     - name: MACGYVER
       run: cmd /c show.bat

     - name: Time Counter
       run: cmd /c loop.bat
